#define NDEF_SUCCESS 0
#define NDEF_ERROR_MALLOC_FAILED -1
#define NDEF_ERROR_TEXT_RECORD_CREATION_FAILED -2
#define NDEF_ERROR_URI_RECORD_CREATION_FAILED -3
#define NDEF_ERROR_MIME_MEDIA_RECORD_CREATION_FAILED -4
#define NDEF_ERROR_EXTERNAL_TYPE_RECORD_CREATION_FAILED -5