#define NDEF_SUCCESS 0
#define NDEF_ERROR_MALLOC_FAILED -1
#define NDEF_ERROR_URI_PAYLOAD_FAILURE -2
#define NDEF_ERROR_RECORD_DECODE_INVALID_LENGTH -3
#define NDEF_ERROR_RECORD_DECODE_CHUNK_NOT_SUPPORTED -4
#define NDEF_ERROR_TEXT_RECORD_CREATION_FAILED -5
#define NDEF_ERROR_URI_RECORD_CREATION_FAILED -6
#define NDEF_ERROR_RECORD_ENCODE_MALLOC_FAILED NULL