#include "ArduinoNDEF/constants.hpp"
#include "ArduinoNDEF/message.hpp"
#include "ArduinoNDEF/record.hpp"
#include "ArduinoNDEF/record/empty.hpp"
#include "ArduinoNDEF/record/external_type.hpp"
#include "ArduinoNDEF/record/mime_media.hpp"
#include "ArduinoNDEF/record/text.hpp"
#include "ArduinoNDEF/record/uri.hpp"