#define NDEF_SUCCESS 0
#define NDEF_ERROR_MALLOC_FAILED -1
#define NDEF_ERROR_URI_PAYLOAD_FAILURE -2
#define NDEF_RECORD_DECODE_ERROR_INVALID_LENGTH -3
#define NDEF_RECORD_DECODE_ERROR_CHUNK_NOT_SUPPORTED -4
#define NDEF_RECORD_ENCODE_ERROR_MALLOC_FAILED NULL