#include "MFRC522v2-NDEF/constants.hpp"
#include "MFRC522v2-NDEF/message.hpp"
#include "MFRC522v2-NDEF/record.hpp"
#include "MFRC522v2-NDEF/record/external_type.hpp"
#include "MFRC522v2-NDEF/record/mime_media.hpp"
#include "MFRC522v2-NDEF/record/text.hpp"
#include "MFRC522v2-NDEF/record/uri.hpp"