name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install valgrind
      - name: Clone dependencies
        run: |
          cd ..
          git clone https://github.com/bxparks/EpoxyDuino
          git clone https://github.com/bxparks/AUnit
      - name: Run tests
        run: |
          make test
