name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone dependencies
        run: |
          cd ..
          git clone https://github.com/bxparks/EpoxyDuino
          git clone https://github.com/bxparks/AUnit
      - name: Run tests
        run: |
          make -C tests
          make -C tests runtests
